Suggested onboarding changes
ButterCMS/django-starter-buttercms pull request #1
Opened 2021-11-22 19:56 UTC by jakelumetta

See my feedback in Trello for more context.

2021-11-23 15:06 UTC, ViolanteCodes reviewed
Just a few quick things I'm wondering about:

1. Since the secret_key is hard-coded into the file and will be the same for everyone, I wonder if maybe it would be a good idea to change the secret_key in settings/local.py to something like `set_your_secret_key_in_env` and explicitly telling people how to set it in the readme?

Or even better, just not having a default secret key set, and having people set their secret key in readme as part of the FAQ. Otherwise, if they push a fork to git, etc., they're going to get warnings and whatnot - I realize that they're not important warnings if you take a moment to crawl through the repo and establish, okay, yeah, this key is just a default - but I wonder if it would be a good idea to do this in an effort to make the process friction-free (e.g., I as a user don't have to go check and see how it's handled before push.)

2. Is it possible that someone accidentally sets their api token to <Your Api Token> or whatever and doesn't actually have an API token set, thereby not connecting to butter? What happens if they do? Does the check for the API token come on the project launch, then (e.g., when they open the project in localhost, is that when they'll see that their API token is wrong?) (This isn't a criticism at all, just like, a question in my head.)

3. I noticed that there's no link to the readme to any of the sections in the butter docs for more information. I'm wondering if it might be a good idea to furnish a link, e.g., "For more information, you can refer to our docs at "https://buttercms.com/docs/". You can also view information about our rest API at "https://buttercms.com/docs/api/". (I used the general docs link and not the django specific link because it would only be one extra click to take them to Django, but the wall of framework buttons is pretty impressive in case they're on the fence about using django for the final project, and there's less chance of the link not being updated when copy - paste instructions from one starter project to the next.)

2021-11-23 17:43 UTC, ViolanteCodes commented
@jakelumetta I did a review of just the files that have changed, because I wasn't sure as to scope of the review - did you want me to also go through the whole project?

2021-11-24 11:40 UTC, orlyohreally commented on README.md
>  ### Run the local server
I like the idea, so I only slightly rephrased your text to better fit with the next.js command

2021-11-24 17:21 UTC, ViolanteCodes requested changes
Video With Summary of Aesthetic / Functional Review: https://share.getcloudapp.com/P8u8O5QY

1. During the install requirements phase, I got a series of errors that ended in:
```
error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2
  ERROR: Failed building wheel for termcolor
```

If I did a `pip install wheel first`, these errors went away. It looks like venv doesn't install wheel automatically the way virtualenv does, so I think if we want to use venv, with need to both` pip install --upgrade pip` and then also `pip install wheel`

2. Once I completed the readme, I tried to runserver, but got an error message: 

```
(venv) maria@maria-Galago-Pro:~/Programming/butter/django-starter-buttercms$ python manage.py runserver
Traceback (most recent call last):
  File "/home/maria/Programming/butter/django-starter-buttercms/venv/lib/python3.8/site-packages/environ/environ.py", line 367, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'
...(truncated here)
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
```

There isn't a sample env file anymore, so I think we should probably add the environmental variable step from the readme?

3. API token handing for improper API token (see video) - if API token is set but set to a token that doesn't exist, the user is brought to a django `page not found` debug page with no other information - we should probably catch this somehow? I'm also wondering re: what happens when token expires?

4. Footer menus on all pages except for index are broken (should navigate back to main page) **(now fixed)**

5. Blog post button is missing from index page - so there's no way to navigate to the blog without clicking a post first and backing up to blog through breadcrumb menu.

6. I'm wondering about attractive handling of missing featured images (see video)

7. Search functionality in blog pages doesn't appear to be working? The button doesn't connect to the search. The url appears to be set up (I tried typing in manually) but then only the header and footer load.

There are also some smaller items. I tried to notate everything in the checklist below:

## Index View
[ ] Detects if API token is configured and displays error hero if not. **See notes re: improper token**
[x] All menu items in header smooth scroll to appropriate content section.
[x ] All menu items in footer smooth scroll to appropriate content section.
[x] Need an account link routes to appropriate URL in buttercms.com
[x] "Update this page in butter" buttons all link to appropriate butter pages.
[x] Blog section shows up to two cards with most recent blog posts.
[x] "View all blog posts" button on main page links to main blog listview.
[x] Title on each blog card links to blog post detail view.
[x] "Read More" Button on each blog card links to blog post detail view.

## Blog Main View
[x] Route is setup for /blog/
[x] Detects if API token is configured and displays error hero if not.
[x] All menu items in header link to appropriate content section in main view.
[x] All menu items in footer link to appropriate content section in main view. 
[x] Title above breadcrumb menu says "All Blog Posts"
[x] Breadcrumb menu displays "Home" > All Blog Posts.
[x] "Home" in breadcrumb menu links back to starter project index view.
[x] All categories appear on template widget and are updating with changes.
[x] Clicking on a category routes to the appropriate blog category view.
[x] Posts are displaying, including titles, images, author, date, and tags. **date time weird looking**
[x] Post titles, images, author, date, and tags are updating with changes to posts.
[x] Clicking a tag routes to the appropriate blog tag list view.
[] Title on each blog card links to blog post detail view. **titles do not link**
[x] "Read More" Button on each blog card links to blog post detail view.
[] Search this site button routes to the blog search list view. **search not working for me**

## Blog Categories View
[x] Route is setup for /blog/category/<category-slug>/
[x] Detects if API token is configured and displays error hero if not.
[x] All menu items in header link to appropriate content section in main view.
[x] All menu items in footer link to appropriate content section in main view.
[x] Title above breadcrumb menu says "Blog Posts By Category"
[x] Breadcrumb menu displays "Home" > "Blog" > "Category: <category name>".
[x] "Home" in breadcrumb menu links back to starter project index view.
[x] "Blog" in breadcrumb menu links back to blog list view.
[x] All categories appear on template widget and are updating with changes.
[x] Clicking on a category routes to the appropriate blog category view.
[x] Posts are displaying, including titles, images, author, date, and tags.
[x] Post titles, images, author, date, and tags are updating with changes to posts.
[x] Clicking a tag routes to the appropriate blog tag list view.
[] Title on each blog card links to blog post detail view. **broken**
[x] "Read More" Button on each blog card links to blog post detail view.
[] Search this site button routes to the blog search list view. **broken**


## Blog Tags View
[x] Route is setup for /blog/tag/<tag-slug>/
[x] Detects if API token is configured and displays error hero if not.
[x] All menu items in header link to appropriate content section in main view.
[x] All menu items in footer link to appropriate content section in main view.
[x] Title above breadcrumb menu says "Blog Posts by Tag"
[x] Breadcrumb menu displays "Home" > "Blog" > "Tag: <tag name>".
[x] "Home" in breadcrumb menu links back to starter project index view.
[x] "Blog" in breadcrumb menu links back to blog list view.
[x] All categories appear on template widget and are updating with changes.
[x] Clicking on a category routes to the appropriate blog category view.
[x] Posts are displaying, including titles, images, author, date, and tags.
[x] Post titles, images, author, date, and tags are updating with changes to posts.
[x] Clicking a tag routes to the appropriate blog tag list view.
[] Title on each blog card links to blog post detail view. **broken**
[x] "Read More" Button on each blog card links to blog post detail view.
[] Search this site button routes to the blog search list view. **broken**

## Blog Search View
[x] Route is setup for /blog/search/?q=<query>/
[x] Detects if API token is configured and displays error hero if not.
[x] All menu items in header link to appropriate content section in main view. 
[x] All menu items in footer link to appropriate content section in main view.
[x] Title above breadcrumb menu says "Search Results"
[x] Breadcrumb menu displays "Home" > "Blog" > "Search: <search term>".
[x] "Home" in breadcrumb menu links back to starter project index view.
[x] "Blog" in breadcrumb menu links back to blog list view.
[x] All categories appear on template widget and are updating with changes. 
[x] Clicking on a category routes to the appropriate blog category view. 
[] Posts are displaying, including titles, images, author, date, and tags. **doesn’t display**
[] Post titles, images, author, date, and tags are updating with changes to posts. **doesn’t display**
[] Clicking a tag routes to the appropriate blog tag list view. **doesn’t display**
[] Title on each blog card links to blog post detail view. ** doesn’t display **
[] "Read More" Button on each blog card links to blog post detail view. ** doesn’t display **
[] Search this site button routes to the blog search list view. ** doesn’t display**

## Blog Single Post View
[x] Route is setup for /blog/<post-slug>/
[x] Detects if API token is configured and displays error hero if not.
[x] All menu items in header link to appropriate content section in main view.
[x] All menu items in footer link to appropriate co [...]

2021-11-24 17:27 UTC, ViolanteCodes commented on README.md
> +$ python3 -m venv venv
also, i'm wondering if maybe we should include the upgrade pip step (eg pip install --upgrade pip) because if I remember correctly an old version of pip can mess up package installation sometimes?

2021-12-01 16:04 UTC, jakelumetta commented on README.md
> +### Set API Token
```suggestion
### Whatever you want
```

2021-12-01 16:12 UTC, jakelumetta commented on README.md
> +$ python3 -m venv venv
good suggestion will change to `butterenv`

re: `pip install --upgrade pip` unclear if its needed. I think let's keep that outside the scope of the README.md for now unless we see many folks running into any issue

2021-12-01 16:22 UTC, jakelumetta commented on README.md
> +$ echo 'BUTTERCMS_API_TOKEN=your_token' >> .env
I wasn't sure about having `<Your API Token>` with special chars like `<` and spaces as the default value because while I think it works ok in `.env` for this Django project, it may not port well across ALL tech stacks versus a safer value.

I'll change it to `Your_Api_Token`

2021-12-01 16:28 UTC, jakelumetta commented on README.md
>  ### Run the local server
I like the headline change.

The rest, I'm on the fence with. Going to make an assumption this is not the very first Django project someone has ever run. Even if it is, the Django server console log is self explanatory enough where we can omit repeating it in our README.

2021-12-01 16:36 UTC, jakelumetta commented on README.md
> +$ python3 -m venv venv
@ViolanteCodes Ah sorry - I hadn't watched your video yet where you ran into an issue. Thanks for the suggestion reviewing it now.

2021-12-09 21:21 UTC, orlyohreally commented
This dependency didn't get installed for me `psycopg2`, I needed to change it to `psycopg2-binary`. Has anybody encountered the same issue? @failedguidedog @zanderle @ViolanteCodes

2022-01-20 12:46 UTC, closed without merging