Fix heroku  URL + logo, remove deprecated key
ButterCMS/django-starter-buttercms pull request #10
Opened 2022-03-04 15:05 UTC by ViolanteCodes

Trello Card: [1479-add-heroku-deploy-for-gatsby-and-nextjs](https://trello.com/c/by0cH7rw/1479-add-heroku-deploy-for-gatsby-and-nextjs)](https://trello.com/c/by0cH7rw/1479-add-heroku-deploy-for-gatsby-and-nextjs)

While adding heroku deploy buttons for nextjs and gatsbyjs, I noticed that I'd missed updating some things in the deploy settings for the django app. I fixed those, and I've also removed a key, "image", which [has been deprecated](https://devcenter.heroku.com/articles/app-json-schema#image).

Here is also a video of me deploying this from branch, including previewing in butter iframe: [https://share.getcloudapp.com/z8uLAx8G](https://share.getcloudapp.com/z8uLAx8G)

2022-03-06 22:46 UTC, failedguidedog requested changes

2022-03-06 22:46 UTC, failedguidedog commented on app.json
> +    "description": "Drop-in proof-of-concept Gatsby.js app, fully integrated with your ButterCMS account.",
Not Gatsby, right?

```suggestion
    "description": "Drop-in proof-of-concept Django app, fully integrated with your ButterCMS account.",
```

2022-03-06 22:46 UTC, failedguidedog commented on app.json
> +    "logo": "https://cdn.buttercms.com/EaL7vzD5TFugzb8CWUiz",
Q: Is this image OK for a logo? I would assume we'd want to have the ButterCMS logo for this?
Also, according to the docs "Dimensions should be square."

2022-03-06 22:46 UTC, failedguidedog commented on app.json
> +    "repository": "https://github.com/ButterCMS/django-starter-buttercms",
:pray: Thank you for fixing this :1st_place_medal:

2022-03-07 14:22 UTC, ViolanteCodes commented on app.json
> +    "repository": "https://github.com/ButterCMS/django-starter-buttercms",
I mean, it's my mistake - I should've caught it before

2022-03-07 14:22 UTC, ViolanteCodes commented on app.json
> +    "logo": "https://cdn.buttercms.com/EaL7vzD5TFugzb8CWUiz",
Okay, pushed a square version of the logo.

2022-03-07 23:43 UTC, failedguidedog approved these changes
Nicely done! :clap:

2022-03-07 23:43 UTC, merged